### ISSUE TITLE
awesome

### ISSUE THREAD

**Issue by JacksonWang6** [shellqiqi/nju-network-labs#4]
感谢伟大的NJU，又开源了如此优秀的课程，来自弱校的仰望（想请问是一直开源还是学期结束就闭源了啊？

**Comment by shellqiqi** [comment]
一直开源

**Comment by WangAShao** [comment]
非常感谢您的回复,请问一下这门课程对应的视频或者讲义开源吗?如果开源的话可以烦请您发一下链接吗?
